from elasticsearch_dsl import Document, Text, analyzer, Integer, Keyword, Double

class Listing(Document):
    id = Integer()
    listing_url = Text()
    scrape_id = Integer()
    last_scraped = Text(fields={'raw': Keyword()})
    name = Text(analyzer='snowball')
    host_id = Integer()
    price = Integer()
    availability_30 = Integer()
    availability_60 = Integer()
    availability_90 = Integer()
    availability_365 = Integer()
    number_of_reviews = Integer()
    first_review = Text(fields={'raw': Keyword()})
    last_review = Text(fields={'raw': Keyword()})
    review_scores_rating = Integer()
    review_scores_accuracy = Integer()
    review_scores_cleanliness = Integer()
    review_scores_checkin = Integer()
    review_scores_communication = Integer()
    review_scores_location = Integer()
    review_scores_value = Integer()
    overall_rating = Double()