from datetime import datetime
from elasticsearch_dsl import Document, Date, Integer, Keyword, Text, Nested, Double, Index


class ListingDocument(Document):
    id = Integer()
    listing_url = Text()
    scrape_id = Integer()
    last_scraped = Text()
    name = Text()
    description = Text() 
    neighborhood_overview = Text()
    picture_url = Text()
    host_id = Integer()
    host_url = Text()
    host_name = Text()
    host_since = Text()
    host_location = Text()
    host_about = Text()
    host_response_time = Text() 
    host_response_rate = Text()
    host_acceptance_rate = Text()
    host_is_superhost = Text()
    host_thumbnail_url = Text()
    host_picture_url = Text()
    host_neighbourhood = Text()
    host_listings_count = Integer()

    host_total_listings_count = Integer()
    host_verifications = Text(fields={'keyword': Keyword()})
    host_has_profile_pic = Text()
    host_identity_verified = Text()
    neighbourhood = Text()
    neighbourhood_cleansed = Text()
    neighbourhood_group_cleansed = Text() #
    latitude = Double()
    longitude = Double()
    property_type = Text()
    room_type = Text()
    accommodates = Text()
    bathrooms = Text()
    bathrooms_text = Text()
    bedrooms = Integer()
    beds = Text()
    amenities = Text(fields={'keyword': Keyword()})
    
    price = Text()
    minimum_nights = Integer()
    maximum_nights = Integer()
    minimum_minimum_nights = Integer()
    maximum_minimum_nights = Integer()
    minimum_maximum_nights = Integer()
    maximum_maximum_nights = Integer()
    minimum_nights_avg_ntm = Integer()
    maximum_nights_avg_ntm = Integer()
    calendar_updated = Text() #
    has_availability = Text()
    availability_30 = Integer()
    availability_60 = Integer()
    availability_90 = Integer()
    availability_365 = Integer()

    calendar_last_scraped = Text()
    number_of_reviews = Integer()
    number_of_reviews_ltm = Integer()
    number_of_reviews_l30d = Integer()
    first_review = Text()
    last_review = Text()
    
    review_scores_rating = Double()
    review_scores_accuracy = Double()
    review_scores_cleanliness = Double()
    review_scores_checkin = Double()
    review_scores_communication = Double()
    review_scores_location = Double()
    review_scores_value = Double()

    license = Text()
    instant_bookable = Text()
    calculated_host_listings_count = Integer()
    calculated_host_listings_count_entire_homes = Integer()
    calculated_host_listings_count_private_rooms = Integer()
    calculated_host_listings_count_shared_rooms = Integer()
    reviews_per_month = Double()

    class Index:
        name = 'listing'

