import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.json4s._
import org.json4s.jackson.JsonMethods._
import com.fasterxml.jackson.core.JsonParseException
import java.net.URLEncoder

/********** UI Event **********/

// Schema for UI event
val request_schema = new StructType()
      .add("query", StringType)
      .add("sort", new StructType()
          .add("id", StringType)
          )
      .add("page", new StructType()
          .add("size", StringType)
          .add("current", StringType)
          )


// Schema for search result
val result_schema = new StructType()
      .add("meta", new StructType()
          .add("page", new StructType()
	          .add("current", StringType)
	          .add("total_pages", StringType)
	          .add("total_results", StringType)
	          .add("size", StringType)
	          )
          .add("engine", new StructType()
	          .add("name", StringType)
	          )
          .add("request_id", StringType)
       )
      .add("results", new ArrayType(new StructType()
          .add("id", new StructType()
	          .add("raw", StringType)
	          )
          .add("index", new StructType()
	          .add("snippet", StringType)
	          )
          .add("name", new StructType()
	          .add("snippet", StringType)
	          )
          .add("availability_30", new StructType()
	          .add("snippet", StringType)
	          )
          .add("listing_url", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_rating", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_cleanliness", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_communication", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_checkin", new StructType()
	          .add("snippet", StringType)
	          )
          .add("availability_90", new StructType()
	          .add("snippet", StringType)
	          )
          .add("availability_365", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_accuracy", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_location", new StructType()
	          .add("snippet", StringType)
	          )
          .add("review_scores_value", new StructType()
	          .add("snippet", StringType)
	          )
          .add("availability_60", new StructType()
	          .add("snippet", StringType)
	          )
          .add("scrape_id", new StructType()
	          .add("snippet", StringType)
	          )
          .add("last_scraped", new StructType()
	          .add("snippet", StringType)
	          )
          .add("host_id", new StructType()
	          .add("snippet", StringType)
	          )
          .add("first_review", new StructType()
	          .add("snippet", StringType)
	          )
          .add("last_review", new StructType()
	          .add("snippet", StringType)
	          )
          .add("overall_rating", new StructType()
	          .add("snippet", StringType)
	          )
          .add("price", StringType),
            true)
          )